### ISSUE TITLE
docker composer build version not being displayed after installing

### ISSUE THREAD

**Issue by nischith2002** [UniCourt/DataEngineering-Workshop1#4]
I Installed docker composer accordingly by first installing Docker followed by docker composer.when I tried to run the command for viewing the version of composer , composer  version is being displayed were as build version is not being displayed
![Screenshot from 2022-08-20 20-57-42](https://user-images.githubusercontent.com/109530352/185754591-43feb2fc-2c1e-4b20-b866-d3f5a9361e9e.png)
d

**Comment by shamiths-uc** [comment]
@nischith2002 Please try below step.

**Step 1:** Download docker-compose from docker’s github repository
curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s\`-\`uname -m` > ~/docker-compose

**Step2:** Set the permissions
`chmod +x ~/docker-compose`

**Step3:**  Move the file
`sudo mv ~/docker-compose /usr/local/bin/docker-compose`

Then you’ll verify that the installation was successful by checking the version
`docker-compose --version`

Also try below step to verify docker-compose is working fine

Create docker-compose.yml YAML file and add below content
`my-test:
    image: hello-world` 
Run below command to create container  
`docker-compose up -d`

Note :  Please ignore above issue if it worked fine

If you get any error then please provide your OS details, docker version and what command you used to install docker and docker-compose.

**Comment by nischith2002** [comment]
[https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname](https://github.com/docker/compose/releases/download/1.27.4/docker-compose-%60uname) -s`-`uname -m` > ~/docker-compose

this link is not working 404 error is being displayed

**Comment by shamiths-uc** [comment]
@nischith2002  Run below curl command in your terminal   
```
curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
```

**Comment by nischith2002** [comment]
thank you
