### ISSUE TITLE
Update the documentation for Dockerfile creation

### ISSUE THREAD

**Issue by ashwathyk-uc** [UniCourt/DataEngineering-Workshop1#7]
- Need mention the filename of Dockerfile
- Need to mention that we need to create a docker file using any editor (vi, vim, nano or gedit)
- Need add a link of dockerhub.
- Add a warning that docker pull limit can be reached and what is the alternative.

**Comment by safwanebrahim-uc** [comment]
@ashwathyk-uc Done in this PR [https://github.com/UniCourt/DataEngineering-Workshop1/pull/8/files](https://github.com/UniCourt/DataEngineering-Workshop1/pull/8/files)

**Comment by ashwathyk-uc** [comment]
Since the suggested changes are made, closing the issue.
