### ISSUE TITLE
Pull request is not working with HTTPS clone

### ISSUE THREAD

**Issue by safwanebrahim-uc** [UniCourt/DataEngineering-Workshop1#9]
if we are cloning the repo with HTTPS option, we cannot create a pull request

**Comment by shamiths-uc** [comment]
@safwanebrahim-uc  Git is removed pushing the code using **HTTPS** :[Please check here ]( https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls). But you can push the code using SSH key.  

Instruction to use ssh key is added [here](https://github.com/UniCourt/DataEngineering-Workshop1#github-account). Please make sure you cloned the repo using **SSH** key.

PR : https://github.com/UniCourt/DataEngineering-Workshop1/pull/8/files

**Comment by safwanebrahim-uc** [comment]
@shamiths-uc Thanks. it worked now
